runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: frontend/css
  mime_type: text/css

- url: /(.*\.(gif|png|jpg))
  static_files: frontend/images/\1
  upload: frontend/images/(.*\.(gif|png|jpg))

- url: /.*
  script: _go_app
